package marshi.owl.data.rdb.entity;

public class TicketSequence {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_sequence.id
     *
     * @mbggenerated Thu Apr 20 23:58:39 JST 2017
     */
    private Long id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_sequence.id
     *
     * @return the value of ticket_sequence.id
     *
     * @mbggenerated Thu Apr 20 23:58:39 JST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_sequence.id
     *
     * @param id the value for ticket_sequence.id
     *
     * @mbggenerated Thu Apr 20 23:58:39 JST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }
}