spring:
  session.store-type: none
  data:
    neo4j:
      uri: http://localhost:7474
      username: neo4j
      password: neo

security:
  basic:
    enabled: false

jdbc:
  datasource:
    owl:
      slave:
        url: jdbc:mysql://localhost/owl
        username: owl_r
        password: ueaQyWQ9Lxsv
        driverClassName: com.mysql.jdbc.Driver
      master:
        url: jdbc:mysql://localhost/owl
        username: owl_w
        password: jY8fqaRV
        driverClassName: com.mysql.jdbc.Driver
