server:
  port: 8001

spring:
  thymeleaf.prefix: classpath:/templates/html/
  session.store-type:
    - springframework.session.jdbc.JdbcOperationsSessionRepository
  devtools.restart:
    additional-paths:
      - web/src/main/resources/templates
      - web/src/main/js

